header_rewrites: []
scriptings:
  - http_response:
      name: Apple Weather Availability
      script_url: >-
        https://raw.githubusercontent.com/VirgilClyne/iRingo/main/js/Weather.Availability.js
      match: ^https?:\/\/weather-data\.apple\.com\/(v1|v2)\/availability\/.*
      body_required: true
  - http_response:
      name: Apple Weather
      script_url: https://raw.githubusercontent.com/VirgilClyne/iRingo/main/js/Weather.js
      match: ^https?:\/\/weather-data\.apple\.com\/(v1|v2)\/weather\/.*
      body_required: true
      timeout: 20
  - http_request:
      name: Apple Weather Map
      script_url: >-
        https://raw.githubusercontent.com/VirgilClyne/iRingo/main/js/Weather.Map.js
      match: >-
        ^https?:\/\/weather-map\.apple\.com\/(v1|v2)\/mapOverlay\/.*(\?.*country=CN.*)
mitm:
  - weather-data.apple.com
  - weather-map.apple.com
